spring:
  ai:
    model:
      chat: openai
      embedding: openai
      audio:
        speech: openai
        transcription: openai
      image: openai
      moderation: openai


    openai:
      api-key: ${openai_api_key}